<?php
/**
 * MTASK - Sample Configuration File
 * --------------------------------------------------------------------------
 * This file is a template. The installer (install.php) generates the real
 * config.php from this template using the values you provide in the wizard.
 *
 * Do NOT edit config.php manually unless you know what you are doing.
 *
 * @package MTASK
 */

declare(strict_types=1);

return [
    // ----- Database -----
    'db' => [
        'host'    => '__DB_HOST__',
        'port'    => '__DB_PORT__',
        'name'    => '__DB_NAME__',
        'user'    => '__DB_USER__',
        'pass'    => '__DB_PASS__',
        'charset' => 'utf8mb4',
    ],

    // ----- Application -----
    'app' => [
        'name'        => 'MTASK',
        'base_url'    => '__BASE_URL__',   // e.g. https://example.com
        'environment' => 'production',     // production | development
        'timezone'    => 'UTC',
    ],

    // ----- Security -----
    'security' => [
        // Random 64 char key generated by the installer.
        'app_key'         => '__APP_KEY__',
        'session_name'    => 'mtask_session',
        'session_lifetime'=> 7200, // seconds
    ],

    // ----- Telegram (also stored in DB settings, kept here as a fallback) -----
    'telegram' => [
        'bot_token' => '__BOT_TOKEN__',
    ],
];
